# Generated by Django 5.0.4 on 2024-05-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100)),
                ('para', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='article_images/')),
                ('date', models.DateField()),
            ],
        ),
    ]
